# Data Preprocessing | IBM SkillsBuild Internship

## Import the required libraries

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Import the dataset

In [32]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values #except for the last column , ie, the 'Purchased' column
y = dataset.iloc[:,-1].values #only the last column

In [33]:
print(x)

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 nan]
 ['China' 35.0 58000.0]
 ['Thailand ' nan 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 nan]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' nan 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' nan 55000.0]
 ['China' 41.0 nan]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


figured that empty values has 'nan' there

In [34]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes'
 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Solving for missing data

In [35]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean') #to use simpleimputer in places of nan(empty values) using mean values
imputer.fit(x[:,1:3]) #to fit imputer in 1st and 2nd column only
x[:,1:3] = imputer.transform(x[:,1:3]) #to change the imputed columns to x

In [36]:
print(x)

[['India' 44.0 72000.0]
 ['Thailand ' 27.0 48000.0]
 ['Indonesia' 30.0 54000.0]
 ['China' 38.0 61000.0]
 ['India' 40.0 62562.5]
 ['China' 35.0 58000.0]
 ['Thailand ' 38.5625 52000.0]
 ['India' 48.0 79000.0]
 ['Indonesia' 50.0 83000.0]
 ['Thailand ' 37.0 67000.0]
 ['India' 25.0 62562.5]
 ['Thailand ' 36.0 60000.0]
 ['Indonesia' 42.0 64000.0]
 ['India' 38.5625 40000.0]
 ['Thailand ' 52.0 90000.0]
 ['Indonesia' 38.5625 55000.0]
 ['China' 41.0 62562.5]
 ['India' 29.0 48000.0]
 ['China' 43.0 70000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [37]:
from sklearn.compose import ColumnTransformer #To transform coumn values

from sklearn.preprocessing import OneHotEncoder #Onehot encoding

ct = ColumnTransformer(transformers= [('encoder',OneHotEncoder(), [0])], remainder='passthrough') #1- us onehotencoder in 0th column , 2- remainder columns: passthrough

x = np.array(ct.fit_transform(x))

In [38]:
print(x)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 0.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 40.0 62562.5]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 38.5625 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 37.0 67000.0]
 [0.0 1.0 0.0 0.0 25.0 62562.5]
 [0.0 0.0 0.0 1.0 36.0 60000.0]
 [0.0 0.0 1.0 0.0 42.0 64000.0]
 [0.0 1.0 0.0 0.0 38.5625 40000.0]
 [0.0 0.0 0.0 1.0 52.0 90000.0]
 [0.0 0.0 1.0 0.0 38.5625 55000.0]
 [1.0 0.0 0.0 0.0 41.0 62562.5]
 [0.0 1.0 0.0 0.0 29.0 48000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]]


### Encoding the Dependent Variable

In [39]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
y = le.fit_transform(y)

In [40]:
print(y)

[0 1 0 0 1 1 0 1 0 1 0 0 1 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2 ,random_state=0 )

In [42]:
print(x_test)

[[0.0 1.0 0.0 0.0 25.0 62562.5]
 [0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 0.0 43.0 70000.0]]


## Feature Scaling

In [43]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [44]:
print(x_train)

[[-0.5        -0.70710678 -0.5         1.6583124   2.22042763  2.385368  ]
 [ 2.         -0.70710678 -0.5        -0.60302269  0.31534835  0.07474013]
 [-0.5        -0.70710678 -0.5         1.6583124  -0.1067999  -0.81477265]
 [-0.5         1.41421356 -0.5        -0.60302269  0.14215933  0.07474013]
 [-0.5        -0.70710678  2.         -0.60302269 -1.58973093 -0.6463442 ]
 [ 2.         -0.70710678 -0.5        -0.60302269 -0.7237858  -0.30948729]
 [-0.5         1.41421356 -0.5        -0.60302269 -0.1067999  -1.82534339]
 [-0.5        -0.70710678 -0.5         1.6583124  -0.37740775  0.44844076]
 [-0.5         1.41421356 -0.5        -0.60302269  1.52767153  1.4590115 ]
 [-0.5         1.41421356 -0.5        -0.60302269 -1.76291995 -1.15162956]
 [-0.5        -0.70710678 -0.5         1.6583124  -0.55059678 -0.14105883]
 [ 2.         -0.70710678 -0.5        -0.60302269 -0.20421873 -0.0568446 ]
 [-0.5         1.41421356 -0.5        -0.60302269  0.83491543  0.8695119 ]
 [-0.5        -0.70710678

In [45]:
print(x_test)

[[-0.57735027  1.73205081 -0.57735027 -0.57735027 -1.06451121 -0.26295354]
 [-0.57735027 -0.57735027 -0.57735027  1.73205081 -0.87526477 -1.41352962]
 [-0.57735027 -0.57735027  1.73205081 -0.57735027  1.30106925  1.35180343]
 [ 1.73205081 -0.57735027 -0.57735027 -0.57735027  0.63870672  0.32467973]]
